<?php

///**
// * Show form once callback has fired.
// * @return mixed
// */
//function checklist_inspections_page() {
//  if(!user_access('view checklist inspections')) {
//    return MENU_ACCESS_DENIED;
//  }
//  return drupal_get_form('checklist_inspections_form');
//
//}
//
///**
// * Implements hook_form().
// * Checklist Inspections Form
// */
//function checklist_inspections_form($form, &$form_state) {
//
//  $form = array();
//
//
//
//  return $form;
//}